name: tender_ui
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.9
  go_router: ^12.1.1
  url_launcher: ^6.2.5
  envied: ^0.5.1
  http: ^0.13.6
  photo_view: ^0.14.0
  socket_io_client: ^2.0.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  envied_generator: ^0.5.1
  build_runner: ^2.4.8


flutter:
  uses-material-design: true
  assets:
  - assets/images/
